### ISSUE TITLE
Unknown function: getcurpos

### ISSUE THREAD

**Issue by Dhq** [wincent/scalpel#4]
I just tried installing the plugin for gvim on Windows (10), and get this error on every cursor move:

**Error detected while processing CursorMoved Auto commands for "*":
E117: Unknown function: getcurpos**

Installed Scalpel through [vim-plug](https://github.com/junegunn/vim-plug) and using vim 7.4

**Comment by wincent** [comment]
What exact version of Vim is it? (ie. what is the output of `:version` in Vim?)

The `getcurpos` function was added in Vim commit 6f6c0f8085a5b0855f9dce8378086fd5e06a219b (tag: v7.4.313), as far as I know. If you can confirm that's your issue I'll try to find a backwards compatible solution.

**Comment by Dhq** [comment]
@wincent Sorry for late reply. Since I had this issue I have re-installed VIM because of another issue, and I no longer have this problem, most likely due to having a newer version now.
